# Font settings
font_family      UbuntuMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --------------------------
# Kitty Gruvbox Dark Hard Theme (Green → Aqua)
# --------------------------

# Background & Foreground
background #0f1010
foreground #f9f5d7
cursor #ebdbb2
cursor_text_color #0f1010

# Selection
selection_background #458588
selection_foreground #ebdbb2

# Normal colors
color0  #0f1010
color1  #cc241d
color2  #689d6a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #a89984

# Bright colors
color8  #a89984
color9  #cc241d
color10 #689d6a
color11 #d79921
color12 #458588
color13 #b16286
color14 #689d6a
color15 #ebdbb2

# Tabs
active_tab_background   #0f1010
active_tab_foreground   #ebdbb2
inactive_tab_background #1a1b1b
inactive_tab_foreground #bdae93
tab_bar_background      #0f1010
tab_bar_foreground      #d5c4a1

# Scrollbar
scrollbar_thumb #458588
scrollbar_track #1a1b1b

# URL color
url_color #689d6a

# Bold text
bold_text_color #ebdbb2
enable_bold true

# Cursor
cursor_shape block
cursor_blink true

# Bell
bell_animation none

