music_directory     "/home/shrek/Music"
playlist_directory "/home/shrek/.config/mpd/playlists"
db_file             "/home/shrek/.config/mpd/database"
log_file            "/home/shrek/.config/mpd/log"
state_file          "/home/shrek/.config/mpd/state"
sticker_file        "/home/shrek/.config/mpd/sticker.sql"

bind_to_address "127.0.0.1"
port "6600"

audio_output {
    type  "pipewire"
    name  "PipeWire Output"
}

replaygain             "track"
replaygain_preamp      "0"
replaygain_missing_preamp  "0"

auto_update "yes"
auto_update_depth "3"

gapless_mp3_playback "yes"
audio_buffer_size   "2048"
buffer_before_play  "30%"

metadata_to_use "artist,album,title,track,name,genre,date,composer,performer"

decoder {
    plugin "wildmidi"
    enabled "no"
}

max_output_buffer_size "8192"

